version: '3.8'

services:
  warehouse:
    image: ebrazi/warehouse:latest
    container_name: warehouse_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/warehouse
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
